version: '3'
# volumes:
  # mongo:
  # redpanda:
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080  # redpanda:
  #   image: docker.redpanda.com/vectorized/redpanda:latest
  #   command:
  #     - redpanda start
  #     - --smp 1
  #     - --memory 1G
  #     - --reserve-memory 0M
  #     - --overprovisioned
  #     - --node-id 0
  #     - --check=false
  #     - --pandaproxy-addr INSIDE://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
  #     - --advertise-pandaproxy-addr INSIDE://redpanda:28082,OUTSIDE://localhost:8082
  #     - --kafka-addr INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
  #     - --advertise-kafka-addr INSIDE://redpanda:29092,OUTSIDE://localhost:9092
  #     - --rpc-addr 0.0.0.0:33145
  #     - --advertise-rpc-addr redpanda:33145
  #   volumes:
  #     - redpanda:/var/lib/redpanda/data
  #   ports:
  #     - 8081:8081
  #     - 8082:8082
  #     - 9092:9092
  #     - 9644:9644
  # redpanda-ui:
  #   image: docker.redpanda.com/vectorized/console:latest
  #   entrypoint: /bin/sh
  #   command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
  #   environment:
  #     CONFIG_FILEPATH: /tmp/config.yml
  #     CONSOLE_CONFIG_FILE: |
  #       kafka:
  #         brokers: ["redpanda:29092"]
  #         schemaRegistry:
  #           enabled: false
  #           urls: ["http://redpanda:8081"]
  #       redpanda:
  #         adminApi:
  #           enabled: true
  #           urls: ["http://redpanda:9644"]
  #       connect:
  #         enabled: false
  #         clusters:
  #           - name: local-connect-cluster
  #             url: http://redpanda:8083
  #   ports:
  #     - 8014:8080
  #   depends_on:
  #     - redpanda
  # mongo: 
  #   image: mongo:7
  #   restart: always
  #   ports: 
  #     - 27017:27017
  #   volumes:
  #     - mongo:/data/db
  rabbitmq:
   image: rabbitmq:3-management
   restart: always
   ports:
     - 5672:5672
     - 15672:15672